_BASE_: '../Base-RCNN-FPN.yaml'
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 8
DATASETS:
  TRAIN:
  - kins2020_train
  TEST:
  - kins2020_test
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.0025
  STEPS: (30000, 40000)
  MAX_ITER: 48000
  #OPT_TYPE: "SGD"
  CHECKPOINT_PERIOD: 16000
TEST:
  EVAL_PERIOD: 16000
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 3000
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 3000

