_BASE_: './Base-RCNN-FPN-KINS2020.yaml'
OUTPUT_DIR: ../data/train_outputs/aistron/maskrcnn/maskrcnn_R101_FPN_kins2020_6ep_bs1/
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101