_BASE_: './Base-RCNN-FPN-COCOA-cls.yaml'
OUTPUT_DIR: ../data/train_outputs/aistron/bcnet/bcnet_R50_FPN_cocoa_cls_8ep_bs2/
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/new_baselines/mask_rcnn_R_50_FPN_400ep_LSJ/42019571/model_final_14d201.pkl" 
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_MASK_HEAD:
    NAME: BCNet 