_BASE_: '../Base-RCNN-FPN.yaml'
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("cocoa_cls_train",)
  TEST: ("cocoa_cls_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0005
  STEPS: (5000, 8000)
  MAX_ITER: 10000
TEST:
  EVAL_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MASK_FORMAT: "bitmask"
