_BASE_: './aisformer_R101_FPN_cocoa_8ep_bs2.yaml'
OUTPUT_DIR: ../data/train_outputs/aistron/aisformer/aisformer_R50_FPN_cocoa_8ep_bs2/
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/new_baselines/mask_rcnn_R_50_FPN_400ep_LSJ/42019571/model_final_14d201.pkl" 
  RESNETS:
    DEPTH: 50