_BASE_: './Base-RCNN-FPN-COCOA.yaml'
OUTPUT_DIR: ../data/train_outputs/aistron/aisformer/aisformer_R101_FPN_cocoa_8ep_bs2/
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/new_baselines/mask_rcnn_R_101_FPN_400ep_LSJ/42073830/model_final_f96b26.pkl" 
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_MASK_HEAD:
    NAME: AISFormer
AISFORMER:
  INVISIBLE_MASK_LOSS: True
  N_LAYERS: 1
  N_HEADS: 2
  EMB_DIM: 256