_BASE_: '../Base-RCNN-FPN.yaml'
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("coco_train",)
  TEST: ("cocoa_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
