_BASE_: './bcnet_R50_FPN_kins2020_6ep_bs1.yaml'
OUTPUT_DIR: ../data/train_outputs/aistron/bcnet/bcnet_R101_FPN_kins2020_6ep_bs1/
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
