_BASE_: './Base-RCNN-FPN-D2SA.yaml'
OUTPUT_DIR: ../data/train_outputs/aistron/maskrcnn/maskrcnn_R50_FPN_d2sa_18ep_bs2/
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50